# -*- coding: utf-8 -*-
"""plnUSP_lista1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ig2EVXCj_wPEWwS8_v-mW-Jjvz5pA_Xc

***Curso de Extensão em Processamento de Linguagem Natural com Python***
---
*Instituto de Ciências Matemáticas e de Computação da Universidade de São Paulo (ICMC-USP)*


---
Leandro de Assis Madeira - 2021

Atualizando a biblioteca spaCy
"""

!pip install --upgrade spacy

"""# ***Lista de Exercícios 1***

---
*15 de setembro de 2021*

"""

'''1. Crie três variáveis e atribua os valores a seguir: a=1, b=5.9 e c=‘teste’. 
    A partir disso, retorne o tipo de cada uma das variáveis.'''

a=1
b=5.9
c='teste'
print(type(a))
print(type(b))
print(type(c))

'''2. Troque o valor da variável a por ‘1’ e verifique 
    se o tipo da variável mudou.'''

a='1'
print(type(a))

'''3. Faça a soma da variável b com a variável c. Interprete a saída, tanto em 
    caso de execução correta quanto em caso de execução com erro.'''

b+c #operação não suportada pelos dados serem de tipos diferentes

'''4. Crie uma lista com números de 0 a 9 (em qualquer ordem). Com ela, faça:
    a. Adicione o número 6
    b. Insira o número 7 na 3ª posição da lista
    c. Remova o elemento 3 da lista
    d. Adicione o número 4
    e. Verifique o número de ocorrências do número 4 na lista'''

l = list(range(10))
l.append(6)
l.insert(2,7)
l.remove(3)
l.append(4)
l.count(4)
l

'''5. Ainda com a lista criada na questão anterior, faça:
    a. Retorne os primeiros 3 elementos da lista
    b. Retorne os elementos que estão da 3ª posição até a 7ª posição da lista
    c. Retorne os elementos da lista de 3 em 3 elementos
    d. Retorne os 3 últimos elementos da lista
    e. Retorne todos os elementos menos os 4 últimos da lista'''

l[:3]
l[2:7]
l[::3]
l[-3:]
l[:-4]

'''6. Com a lista das questões anteriores, retorne o 6º elemento da lista.'''
l[5]

'''7. Altere o valor do 7º elemento da lista para o valor 12.'''
l.remove(l[6])
l.insert(6, 12)
l

'''8. Inverta a ordem dos elementos na lista.'''
l.reverse()
l

'''9. Ordene a lista.'''
l.sort()
l

'''10. Crie uma tupla com números de 0 a 9 (em qualquer ordem) e tente:
    a. Alterar o valor do 3º elemento da tupla para o valor 10
    b. Verificar o índice (posição) do valor 5 na tupla'''

t = tuple(range(9))
# t[2] = 10 não se altera tuplas
t.index(5)

'''11. Crie um dicionário com 5 entradas e suas respectivas chaves e valores. 
    Faça:
    a. Imprima todas as chaves do dicionário
    b. Imprima todos os valores do dicionário
    c. Imprima todos os itens do dicionário
    d. Imprima o 2º item do dicionário
    e. Imprima o dicionário completo
    f. Percorra o dicionário, imprimindo para cada entrada o modelo “(chave)
    tem como valor (valor)”'''

dic = {}
dic['a'] = 1
dic['b'] = 2
dic['c'] = 3
dic['d'] = 4
dic['e'] = 5
print("Chaves = ", dic.keys())
print("Valores = ", dic.values())
print("Todos os itens: ", dic.items())
print("2º item do dicionário: ", {dic['b']})
for i, j in dic.items():
  print(i, "tem como valor: ", j)

'''12. Crie um arquivo e:
    a. Escreva nele os números de 1 a 10
    b. Depois de escrito, imprima na tela todos os números do arquivo
    c. Escreva no arquivo os números de 11 a 20, substituindo os números que
    estavam antes no arquivo
    d. Escreva no arquivo os números de 21 a 30, adicionando os números no
    final do arquivo (sem apagar o que já estavam lá)
    e. Imprima na tela todos os números do arquivo novamente (de 11 a 30)
    f. Imprima na tela todos os números do arquivo novamente, mas agora
    linha por linha'''

outfile = open("result.txt", 'w')

outfile.write("Números de 1 a 10\n")
for i in range(1,11):
  outfile.write(str(i) + '\n')

outfile = open("result.txt", 'a')

outfile.write("Adicionando números de 11 a 20\n")
for i in range(11,21):
  outfile.write(str(i) + '\n')

